name: instagram
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  flutter_inappwebview: ^6.0.0
  google_sign_in: ^5.0.7
  sqflite: ^2.2.0+3
  syncfusion_flutter_datepicker: ^27.1.58
  path_provider: ^2.0.13
  path: ^1.9.0
  arcore_flutter_plugin: ^0.1.0
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  youtube_player_flutter: ^9.0.4
  firebase_core: ^3.7.0
  video_player: ^2.9.0
  flutter_screenutil: ^5.9.3
  firebase_auth: ^5.3.2
  url_launcher: ^6.1.7
  arkit_plugin: ^1.1.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/

  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf
